### ISSUE TITLE
find() sporadically raises KeyError from cache

### ISSUE THREAD

**Issue by tharradine** [fsspec/s3fs#474]
**What happened**:
The code which failed in this case has worked thousands of times before, but just randomly failed once for us recently. We are just listing all files (with no max-depth) beneath a certain path with `fs.find(prefix)`, and it raises a KeyError on some path *beneath* that prefix:

```
[INFO]	2021-04-29T15:55:02.30Z 	Listing versions beneath 'BUCKET_NAME/prediction/refs/tags'
'BUCKET_NAME/prediction/refs/tags/v6.0.0.dev23': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_handler.py", line 37, in main
    payload = handler(event)
  File "/opt/python/api/handlers.py", line 124, in post_model
    config, user, tags, description, agent_run=runid.agentrun
  File "/opt/python/api/components/abc/abc.py", line 55, in submit_job
    version = cls._validate_version(config)
  File "/opt/python/api/components/abc/abc.py", line 265, in _validate_version
    include_prereleases=True
  File "/opt/python/api/components/abc/abc.py", line 225, in list_releases
    versions = cls.list_versions(tags_only=True)
  File "/opt/python/api/components/abc/abc.py", line 196, in list_versions
    files = fs.find(str(prefix))
  File "/opt/python/fsspec/spec.py", line 434, in find
    for _, dirs, files in self.walk(path, maxdepth, detail=True, **kwargs):
  File "/opt/python/fsspec/spec.py", line 413, in walk
    yield from self.walk(d, maxdepth=maxdepth, detail=detail, **kwargs)
  File "/opt/python/fsspec/spec.py", line 383, in walk
    listing = self.ls(path, detail=True, **kwargs)
  File "/opt/python/s3fs/core.py", line 619, in ls
    files = self._ls(path, refresh=refresh)
  File "/opt/python/s3fs/core.py", line 487, in _ls
    return self._lsdir(path, refresh)
  File "/opt/python/s3fs/core.py", line 413, in _lsdir
    return self.dircache[path]
  File "/opt/python/fsspec/dircache.py", line 62, in __getitem__
    return self._cache[item]  # maybe raises KeyError
KeyError: 'BUCKET_NAME/prediction/refs/tags/v6.0.0.dev23'
```

**What you expected to happen**:
I don't expect `find()` (or `ls()`, `glob()`, etc) to ever raise KeyError.

**Minimal Complete Verifiable Example**:
I can't say that this is verifiable, since this happened once amongst a very large number of successful runs. I've verified that nothing was occurring on the target S3 bucket around the time of the failure. But this is the best I can provide in terms of what was being executed

```python
import s3fs

BUCKET_NAME = "mybucket"  # Replace with an actual bucket name

botoconfig_kwargs = dict(
    region_name="ap-southeast-2",
    retries=dict(mode="standard", max_attempts=20),
)
fs = s3fs.S3FileSystem(
    listings_expiry_time=10,  # seconds
    default_fill_cache=False,
    default_cache_type="none",
    config_kwargs=botoconfig_kwargs,
)

fs.find(f"{BUCKET_NAME}/subfolder")
```

**Anything else we need to know?**:
In this particular case, `BUCKET_NAME/prediction/refs/tags/v6.0.0.dev23` (the path which the KeyError was raised from) is an S3 prefix which has had files living beneath it for months.

I would love to upgrade to the new version of s3fs, but since it's moved to using asyncio in the background, it is rather unstable on Python 3.6. However since this issue seems to come from the cache, I don't know if this is something which has actually changed since s3fs version 0.4.2 / fsspec 0.8.7? 

Any help would be greatly appreciated, thanks.

**Environment**:

- Dask version: Not using Dask
- s3fs version: 0.4.2
- fsspec version: 0.8.7
- Python version: 3.6 (from AWS Lambda python3.6 runtime, unsure of specific version)
- Operating System: Linux (on AWS Lambda, unsure of specifics)
- Install method (conda, pip, source): pip installed into local directory, then zipped up for deployment to AWS Lambda.

**Comment by martindurant** [comment]
This was probably fixed by https://github.com/dask/s3fs/pull/471

**Comment by tharradine** [comment]
I think you're right, I haven't seen this since upgrading. Cheers!
