### ISSUE TITLE
Cannot access file stored in MinIO through s3fs

### ISSUE THREAD

**Issue by tgaddair** [fsspec/s3fs#482]
**What happened**:

Using the latest version of `s3fs`, we get the following error when attempting to open a remote file:

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (PreconditionFailed) when calling the GetObject operation: At least one of the pre-conditions you specified did not hold

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/s3fs/core.py", line 1834, in _fetch_range
    req_kw=self.req_kw,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/s3fs/core.py", line 1975, in _fetch_range
    **req_kw,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/home/ray/anaconda3/lib/python3.7/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
OSError: [Errno 22] At least one of the pre-conditions you specified did not hold

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  <redacted>
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/utils/data_utils.py", line 109, in read_xsv
    dialect = csv.Sniffer().sniff(csvfile.read(1024 * 100),
  File "/home/ray/anaconda3/lib/python3.7/site-packages/fsspec/spec.py", line 1449, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/fsspec/caching.py", line 376, in _fetch
    self.cache = self.fetcher(start, bend)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/s3fs/core.py", line 1841, in _fetch_range
    ) from ex
s3fs.utils.FileExpired: [Errno 16] The remote file corresponding to filename <redacted> and Etag "<redacted>" no longer exists.
```

The file is being opened through the `fsspec` entrypoint:

```
of = fsspec.open(url, **storage_options)
with of as f:
    ...
```

The twist here is that the URL is given as `s3`, but the file is actually stored in Azure Blob Storage. We're using the [MinIO Azure Gateway](https://docs.min.io/docs/minio-gateway-for-azure.html) to expose an S3-compatible layer over Azure Blob Storage.

Storage options are fairly straightforward for MinIO:

```
storage_options = {
        'endpointUrl': 'http://localhost:9000', 
        'awsAccessKeyId': '...', 
        'awsSecretAccessKey': '...'
}
```

**What you expected to happen**:

Using `s3fs==2021.4.0`, this operation works fine.

**Minimal Complete Verifiable Example**:

Setup MinIO and then provide an s3 path to a bucket/object in MinIO:

```python
url = 's3://bucket/object'
of = fsspec.open(url, **storage_options)
with of as f:
    print(f.read())
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.5.0
- Python version: 3.7.7
- Operating System: Linux (Ubuntu)
- Install method (conda, pip, source): pip

**Comment by tgaddair** [comment]
This issue is still happening with the latest version. @martindurant any thoughts?

**Comment by martindurant** [comment]
Sorry for not noticing this before.
Note that there is also a sister project for direct azure blob access which you may find useful: https://github.com/dask/adlfs

For the specific issue, I'm afraid the traceback s not very informative. Maybe s3fs's file cache has gone out of sync, so you could try running `s3.invalidate_cache()` and see if that helps.

Longer term, t would make a lot of sense to have a minio-based CI run in addition to moto; maybe ETag preconditions do not work the same way under minio.

**Comment by tgaddair** [comment]
Thanks. In our case, we need to go through MinIO as our system is agnostic to the underlying storage (and MinIO provides some useful caching properties).

One thing that is interesting here is that this works fine on GCS, it's only with Azure storage that this error occurs.

Can you think of anything that may have changed between 2021.4.0 and 2021.5.0 that may have contributed to this change in behavior?

Happy to dig into this more on our side. Let me know if there are any pointers towards where I should look to debug this further.

**Comment by martindurant** [comment]
Likely it is the ETag condition, which was brought in so that when you open a file, you don't get data corruption by silently reading from a more recent version, should one appear.

**Comment by martindurant** [comment]
@tgaddair , have you continued to experience this problem or come up with a workaround?

**Comment by tgaddair** [comment]
Hey @martindurant, thanks for checking in. Right now, the workaround is to use v 2021.4.0, unfortunately.

**Comment by djhoese** [comment]
@tgaddair I'm wondering if you've made changes over the last year to get this to work? I'm using a MiniO docker container and when using s3fs I have to specify my endpoint_url as `http://test-minio-server:9000`, but I'm noticing when I do `fs.ls('mybucket')` the bucket name isn't included in the request to MinIO and it fails. But it doesn't fail with an error message it fails with an empty result.

**Comment by d4l3k** [comment]
I had issues getting FSSPEC_S3_ENDPOINT_URL working since it seems to be passed to AioBotoSession incorrectly. For anyone else, I got it working by using a custom FS instead.

```
import s3fs


class MinioFS(s3fs.S3FileSystem):
    """
    A test FS that uses a MinIO filesystem on top of s3fs for TorchX integration
    tests in minikube.
    """

    protocol = ["torchx_minio", "s3", "s3a"]

    def __init__(self, *args: object, **kwargs: object) -> None:
        super().__init__(
            *args,
            key="minio",
            secret="minio123",
            client_kwargs={
                "endpoint_url": "http://minio-service:9000",
            },
            **kwargs
        )
```

https://github.com/pytorch/torchx/pull/696

**Comment by martindurant** [comment]
client_kwargs is accepted by s3fs, so could you show exactly what was not working? It looks like this should be identical to
```
S3FileSystem(key="minio",
            secret="minio123",
            client_kwargs={
                "endpoint_url": "http://minio-service:9000",
            })
```

(separately, https://github.com/fsspec/s3fs/pull/704 made endpoint_url also a top-level kwarg for convenience)

**Comment by d4l3k** [comment]
@martindurant I didn't realize how new `FSSPEC_S3_ENDPOINT_URL` was. I was trying to use it with version 2023.1.0 and running into errors

**Comment by martindurant** [comment]
Ah, indeed, the docs are for the current state of the repo, not the latest package. I suppose that means we ought to release soon.
