### ISSUE TITLE
Drop unnecessary info()/exists() optimisation

### ISSUE THREAD

**Issue by ashnyukov** [fsspec/s3fs#544]
There is an unnecessary usage of list_objects_v2 for getting information of single object.
The head_object request should be faster and cheaper.

The issue was introduced in https://github.com/dask/s3fs/pull/472 and supposed to deal with "expensive head_object calls" from https://github.com/aio-libs/aiobotocore/issues/866.

The real reason of that "expensiveness" seems to be aiohttp bug fixed here https://github.com/aio-libs/aiohttp/commit/ec11acaa299a24728daf314d66f76a59ae93f89c.

**How to reproduce:**

- Get a code snippet from https://github.com/aio-libs/aiobotocore/issues/866 thread.
- Check bad scenario in following docker container:
```
FROM brunneis/python:3.8.3-ubuntu-20.04 
RUN pip3 install 'aiobotocore==1.2.1' 'aiohttp[sepeedups]==3.6.3' boto3 
ENTRYPOINT ["/bin/bash"]
```
the results:
```
10 sync head_object calls with boto: 0.8503482189998977 
10 sync head_object calls with aiobotocore: 2.0853126459999203 
10 async head_object calls with aiobotocore: 0.2471708049999961
```

- Check good scenario in following docker container:
```
FROM brunneis/python:3.8.3-ubuntu-20.04 
RUN pip3 install 'aiobotocore==1.2.1' 'aiohttp[sepeedups]==3.7.1' boto3 
ENTRYPOINT ["/bin/bash"]
```
the results:
```
10 sync head_object calls with boto: 0.7789823640000577 
10 sync head_object calls with aiobotocore: 0.7651884290000908 
10 async head_object calls with aiobotocore: 0.2377795329998662
```

**General considerations:**
With proper version of aiohttp (>=3.7.1) there is no need to replace head_object calls with list_objects_v2 because the former ones are faster. 

And regardless of speed using list_objects_v2 is x11 times expensive (financially) considering AWS pricing for s3 requests https://aws.amazon.com/s3/pricing (which can be quite an issue for someone)

**Comment by isidentical** [comment]
@ashnyukov would you like to make a PR that gets rid of this listing based system and reverts my initial commit and pins the aiohttp version that fixed it?

**Comment by ashnyukov** [comment]
@isidentical i think that will do

**Comment by ashnyukov** [comment]
https://github.com/dask/s3fs/pull/545

**Comment by ashnyukov** [comment]
seems to be release
