### ISSUE TITLE
put method adds parent directory to target path

### ISSUE THREAD

**Issue by vvvlad** [fsspec/s3fs#560]
I've tried to upgrade from s3fs version 0.5.1 to latest 2021.11.1.
One of the differences is that when using

s3obj.put(lpath=source_path, rpath=target_path, recursive=True)

source_path == D:\examples\parent_dir\

on version 0.5.1 the files would be uploaded to:
target_path\
on version 2021.11.1 the files are uploaded to:
target_path\parent_dir\

Is there a flag or some other workaround that can revert to original functionality?

**Comment by AndreiBarsan** [comment]
I experienced the same issue. I ended up solving by ensuring the left side ends with `/*` but I'm not sure whether this is the correct behavior long term.

**Comment by martindurant** [comment]
Transforming "path/" -> "path/*" isn't a crazy thing that we could well do in get/put/cp. If that makes a lot of these issues go away, it would be worth it.

**Comment by ianthomas23** [comment]
This is now implemented correctly and will be in the next `fsspec` and `s3fs` releases due in the next couple of weeks. We now have explicit documentation at https://filesystem-spec.readthedocs.io/en/latest/copying.html about how various `cp/get/put` scenarios are handled, and this is consistent with the behaviour of command-line `cp`.
