### ISSUE TITLE
docs: Add examples configuration for s3 compatible providers

### ISSUE THREAD

**Issue by Timost** [fsspec/s3fs#566]
Hello,

First of all, thank you for s3fs ! 🙏 

I've been using `fsspec/s3fs` with several "s3 compatible" object storage providers (namely scaleway, ovh and minio) which all require specific configuration parameters. It took me a bit of time for each provider to find the correct configuration parameters and I think it could save everyone some time if the documentation included configuration samples for those providers.

I'm willing to contribute examples to the documentation if you are interested.

If that's the case, I'm thinking of modifying this section https://github.com/fsspec/s3fs/blob/main/docs/source/index.rst#self-hosted-s3
If you have some pointers about where these examples could go, please let me know.

**Comment by martindurant** [comment]
Yes, please do - and that sounds exactly right.

**Comment by Timost** [comment]
Great ! Here you go.

**Comment by pierrel-murmuration** [comment]
Hi,
does someone know whether the OVH example is still correct today ? 
It doesn't work for me, I always get "TypeError: sequence item 0: expected str instance, tuple found".
Thank you

```
s3 = s3fs.S3FileSystem(
   key='ovh-s3-key...',
   secret='ovh-s3-secretkey...',
   endpoint_url='https://s3.GRA.cloud.ovh.net',
   client_kwargs={
      'region_name': 'GRA'
   },
   config_kwargs={
      'signature_version': 's3v4'
   }
)
```

**Comment by Timost** [comment]
I haven't tested since I opened this issue and can no longer test it sorry ! '^^
