### ISSUE TITLE
SSLVerification

### ISSUE THREAD

**Issue by Platob** [fsspec/s3fs#568]
Hello,

Do you know where to get / how to install ssl certificates used by the package ?

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

Br
Nicolas

**Comment by martindurant** [comment]
Are you using a self-hosted s3, or are you getting this from AWS? If the latter, make sure you have updated your system certs (certify, openssl, ca-certificates).

**Comment by Platob** [comment]
self hosteds3 in company, i should see with owners, do you have any options to disable ssl checks to test ? I tried with use_ssl=False or verify=False

**Comment by martindurant** [comment]
There are many ways to do it, please see the botocore documentation. You may just want to set the `AWS_CA_BUNDLE` environment. `use_ssl` and `verify` seem to belong in the `client_kwargs` dict.

**Comment by Platob** [comment]
Awesome, thanks for support :)

**Comment by Platob** [comment]
In case of someone sees this, after checks, it can be fixed for windows os installing only python-certifi-win32 (i had to uninstall certifi before in my case and reinstall it after)
