### ISSUE TITLE
Add ContentType in details

### ISSUE THREAD

**Issue by Platob** [fsspec/s3fs#569]
Hello, is it possible to recover the content type from S3FFS.info ?

**Comment by martindurant** [comment]
That's a reasonable request - it isn't included in the keys used in `._info` (see the [source](https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1037)), and is neither in the key `metadata`. `ContentType` seems to be the ONLY standard HTTP headers that we don't transcribe, aside from server and request UID information.
