### ISSUE TITLE
duplicate keys returned with fs.info

### ISSUE THREAD

**Issue by raybellwaves** [fsspec/s3fs#580]
When doing fs.info on a file on s3 it returns the keys:

- Key
- LastModified
- ETag
- Size
- StorageClass
- type
- size
- name

size is a duplicate of Size and name is a duplicate of Key

**Comment by martindurant** [comment]
Yes, true: name and size are the canonical values used elsewhere in fsspec implementations (and the superclass) and Key and Size are the original  S3 keys. We could consider dropping the latter, but originally we thought to pass all the original keys through.

**Comment by raybellwaves** [comment]
> Yes, true: name and size are the canonical values used elsewhere in fsspec implementations (and the superclass) and Key and Size are the original S3 keys. We could consider dropping the latter, but originally we thought to pass all the original keys through.

Thanks. I see it here:
https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1038-L1047
