### ISSUE TITLE
StorageClass always STANDARD

### ISSUE THREAD

**Issue by shawnmasters** [fsspec/s3fs#586]
I have tried this on 0.6.0 and 2021.7.0.  When I grab the info for an object in a bucket it always returns STANDARD for the StorageClass.  I have tested this on objects in Standard and GDA.  Here are two code snippets.

import s3fs
s3hand=s3fs.S3FileSystem()
s3hand.info("redacted")

and

fd=s3fs.S3File(s3hand, "redacted")
fd.info()

When I use boto3, objects in standard come back as a NoneType and GDA comes back as 'DEEP_ARCHIVE', so I know boto3 sees the difference.

Is there something I should be doing differently or is this a bug?

**Comment by martindurant** [comment]
This would be fixed in https://github.com/fsspec/s3fs/pull/575 , which is not yet merged.

**Comment by efiop** [comment]
Fixed by #575
