### ISSUE TITLE
S3File Checksum

### ISSUE THREAD

**Issue by Hannes237** [fsspec/s3fs#624]
The current checksum method can return an incorrect MD5 checksum if the file was created using a multi part upload. I did a local fix on my own looking like that:

```python
def get_s3_checksum(self, file_path: str) -> int:
    with self.open(file_path, "rb") as f:
        md5 = hashlib.md5()
        while byte_var := f.read(4096):
            md5.update(byte_var)
        readable_hash = md5.hexdigest()
    return int(readable_hash, 16)
```

Maybe someone has a better alternative.

**Comment by Jeffwan** [comment]
```
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 573, in checksum
    return int(info["ETag"].strip('"'), 16)
ValueError: invalid literal for int() with base 16: 'b6e64f35b2cb730d93770942a59b2efa-2'
```

The ETAG from multi-part files will break `int(readable_hash, 16)`. This is a critical problem since `multi-part` is enabled by default for high-level APIs like `s3 cp`.  Can someone take a look the issue?

**Comment by martindurant** [comment]
Can you please point to where in the code you found this line? The current implementation looks like:
```
    async def _checksum(self, path, refresh=False):
        """
        Unique value for current version of file
        """

        info = await self._info(path, refresh=refresh)

        if info["type"] != "directory":
            return int(info["ETag"].strip('"').split("-")[0], 16)
        else:
            return int(tokenize(info), 16)
```

You can see that the hyphen from multi-part-uploads is accounted for, and the gitlog says this hasn't changed in two years. Note that `checksum` gives you *a* unique value for your file, and is not necessarily the value you expect from any particular checksumming algorithm.

**Comment by Jeffwan** [comment]
version:

```
pip3 list | grep s3fs
s3fs                      0.4.2
```

code
```
class S3FileSystem(AbstractFileSystem):
    """
    Access S3 as if it were a file system.

    This exposes a filesystem-like API (ls, cp, open, etc.) on top of S3
    storage.
   .....

    def checksum(self, path, refresh=False):
        """
        Unique value for current version of file

        If the checksum is the same from one moment to another, the contents
        are guaranteed to be the same. If the checksum changes, the contents
        *might* have changed.

        Parameters
        ----------
        path : string/bytes
            path of file to get checksum for
        refresh : bool (=False)
            if False, look in local cache for file details first

        """

        info = self.info(path, refresh=refresh)

        if info["type"] != 'directory':
            return int(info["ETag"].strip('"'), 16)
        else:
            return int(tokenize(info), 16)
```

**Comment by Jeffwan** [comment]
When I build my dependencies, I used `pip install mlflow boto3 s3fs` without specifying the version. I think due to  pip3 choose to use an older version. After I manually change to newer version, it works. Thanks for the pointer

**Comment by martindurant** [comment]
OK, so we close. I have no idea why pip would do that - I suggest pinning/specifying versions where possible, or using conda/mamba.
