### ISSUE TITLE
version 2022.5.0 regression error: ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"

### ISSUE THREAD

**Issue by dmoore247** [fsspec/s3fs#626]
`ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"` error occurs with version 2022.5.0 but not with 2022.3.0.

Failing code running in a databricks notebook
Python 3.7.5
```
%pip install openpyxl s3fs==2022.5.0
```
```
import pandas as pd
import openpyxl
#import s3fs
import copy
import numpy as np
import datetime

pdf = pd.read_csv("s3://bucket/path/file.txt", sep = '|', header = 'infer')
```

**Comment by martindurant** [comment]
This looks like it is happening deep inside aiobotocore. Can you please check is something similar has been reported with them, or if you see the same error with different versions of aiobotocore (with matching botocore, of course).

**Comment by raybellwaves** [comment]
Also seeing this.

aiobotocore==2.3.2
boto3==1.21.21
botocore==1.24.21
s3fs==2022.5.0

More details to follow

**Comment by martindurant** [comment]
Sorry I don't have any clear way to debug this. I hope we hear back from aiobotocore.

**Comment by raybellwaves** [comment]
> Sorry I don't have any clear way to debug this. I hope we hear back from aiobotocore.

Indeed. may be fixed now https://github.com/aio-libs/aiobotocore/commit/14f2dd1231c6aa84655b6e0211c367ab10980d6c
