### ISSUE TITLE
S3FileSystem NotImplementedError

### ISSUE THREAD

**Issue by clayms** [fsspec/s3fs#662]
Code that worked without any issue a few days ago now fails.  

`s3fs.__version__`:  `'2022.10.0'` 

```python
import s3fs

KEY = os.getenv('AWS_ACCESS_KEY_ID')
SECRET_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

fs = s3fs.S3FileSystem(key=KEY, secret=SECRET_KEY)
fs.ls("s3://my-bucket")
```

gives:

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-9ec24d2dd6bc> in <cell line: 2>()
      1 fs = s3fs.S3FileSystem(key=KEY, secret=SECRET_KEY)
----> 2 fs.ls("s3://my-bucket")

/data/code-envs/python/polars/lib/python3.9/site-packages/fsspec/spec.py in ls(self, path, detail, **kwargs)
    338         dicts if detail is True.
    339         """
--> 340         raise NotImplementedError
    341 
    342     def _ls_from_cache(self, path):

NotImplementedError: 

```

**Comment by martindurant** [comment]
I can only suppose you have some environment mismatch between fsspec and s3fs -  please check.

```
fs = s3fs.S3FileSystem()
fs.ls
```
->
```
<function s3fs.core.S3FileSystem._ls(path, detail=False, refresh=False)>
```
(**not** AbstractFileSystem.ls with the not-implemented)

**Comment by clayms** [comment]
@martindurant 

What I get in the same session that has the error. 

```python 
fs = s3fs.S3FileSystem()
fs.ls
```
->
```
<bound method AbstractFileSystem.ls of <s3fs.core.S3FileSystem object at 0x7fd314fa5e20>>
```

**Comment by clayms** [comment]
@martindurant 

How to get around this?

**Comment by clayms** [comment]
Versions of both `fsspec` and `s3fs` .

```
fsspec==2022.10.0
s3fs==2022.10.0
```

**Comment by clayms** [comment]
I think it might be `pyarrow==10.0.0` causing the issue.

https://arrow.apache.org/docs/python/filesystems.html

**Comment by martindurant** [comment]
Honestly, I don't know! If this were happening in the current version of the code, our tests must be failing, so I can only suppose there is something about your system. Would you mind checking your paths (python executable and library paths, PYTHONPATH and current working directory) or maybe reinstalling in a fresh environment? Please document exactly how you installed python, fsspec and s3fs.

**Comment by martindurant** [comment]
> I think it might be pyarrow==10.0.0 causing the issue.

How is arrow related? You didn't even import it in the snippet.

**Comment by clayms** [comment]
Ok, found the issue.  It is the `polars` library.  

Sorry I did not originally include the import, I was trying to be brief.

I'll downgrade to an earlier version of polars and report back.

**Comment by clayms** [comment]
reference
https://pola-rs.github.io/polars-book/user-guide/howcani/io/aws.html

**Comment by clayms** [comment]
downgrading polars to `0.14.17` fixes the issue.  I'll see how high I can go, then report the issue on the polars repo.

**Comment by martindurant** [comment]
Thanks for digging. Please reference your polars issue here.

**Comment by clayms** [comment]
posted on polars repo
https://github.com/pola-rs/polars/issues/5451
