### ISSUE TITLE
use_session_token ignores ~/.aws/credentials

### ISSUE THREAD

**Issue by tranzmatt** [fsspec/s3fs#682]
I have an S3 bucket that requires a session token to access, so I created the ~/.aws/credentials as per the instructions with the 600 permissions,  but when I go to run:

s3fs -f -d -d the-bucket ~/s3-bucket -o use_session_token -o dbglevel=info -f -o curldbg

I get:

s3fs: could not determine how to establish security credentials.

Does the use_session_token ignore ~/.aws/credentials?  I know it can use environment variables, but the s3fs docs say I can use ~/.aws/credentials

I'm on a jammy box running:

      s3fs |     1.90-1 | http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

**Comment by martindurant** [comment]
I'm afraid this is the wrong s3fs! You wanted the linux CLI utility, but ended up at the python package instead.
