### ISSUE TITLE
S3FileSystem ls returning outdated list of keys after S3 bucket contents changed

### ISSUE THREAD

**Issue by tom-pugh** [fsspec/s3fs#703]
I've been working on a project that has an S3 bucket that uploads and deletes files frequently (once a day), and just as frequently the contents need to be checked. These files are not managed using versions, and all have their timestamp in the filename. I've been using `s3fs.S3FileSystem` for checking the contents of this bucket, creating a new instance each time and using the `ls` method (code snippet at bottom).

What I've noticed is that after about a day or two of running the program, `ls` will have stopped returning current keys in the S3 bucket, and instead start to return only an old version of this list of keys. It seems this begins to happen after the contents of the S3 bucket have changed while the program is still running.

I've included a screenshot from our logging platform showing the discrepancy between what is returned using `s3fs.S3FileSystem`'s `ls`, vs `boto3.client("s3")`'s `list_objects`. What's included is the timestamp of the log messages, as well as the timestamps attached to each file to show that there's quite a bit of difference from the two requests. These requests were not made while the contents of the S3 bucket were being changed.
![image](https://user-images.githubusercontent.com/61809812/219551940-c641446d-9b5e-4a93-af05-2ccbf698d6c6.png)
I've blanked out project related information, so apologies for the readability. The last two keys have static names, and as you may be able to see, the timestamps on the other keys are about a day out of date using s3fs compared to boto3 when listing objects in the same S3 bucket.

The code used for fetching the list of keys using s3fs (excluding keys and some logic) was
```py
def fetch_datasets():
  s3 = s3fs.S3FileSystem(key=..., secret=..., client_kwargs=...)
  filenames = s3.ls(...)
  return filenames
```

The code used for fetching the list of keys using boto3 to compare with (excluding keys and some logic) was
```py
def fetch_datasets():
  s3 = boto3.client("s3", aws_secret_key_id=..., aws_secret_access_key=...)
  query = s3.list_objects(Bucket=..., Prefix=..., Delimiter=...)
  filenames = [<list comprehension for getting CommonPrefixes>]
  return filenames
```

As I'm creating a new instance of the S3FileSystem class each time, I wouldn't expect `ls` to return an outdated list of keys. This seems only to happen when the S3 bucket contents have been updated since program start, and the keys have been fetched using `ls` at least once before.

If I'm missing something about this behaviour, or if there's anything I can add, please let me know!

**Comment by martindurant** [comment]
s3fs by default caches filename listings, since fetching them is generally an expensive operation. You can do `filenames = s3.ls(..., refresh=True)` or `fs.invalidate_vache()` to explicitly prevent this at each call. 
Furthermore, you can control the directory caching behaviour via the kwargs use_listings_cache and listings_expiry_time (see fsspec.dircache.DirCache).

**Comment by tom-pugh** [comment]
Apologies for the late response. That helps, thank you! I must have missed that when googling
