### ISSUE TITLE
Transactions are written before exit when using mapper

### ISSUE THREAD

**Issue by ohsqueezy** [fsspec/s3fs#705]
I'm having an issue on version 2023.1.0 while trying to use transactions with a mapper object. In the following, I would expect the file to be written only after the transaction exits, but it is immediately written before the sleep runs. If I use `s3.open` instead, it works, but I don't think it's a usable workaround for `xarray.to_zarr`, which is what I'm trying to use transactions with.

```
import s3fs, time

s3 = s3fs.S3FileSystem()
with s3.transaction:
    m = s3.get_mapper("my-bucket/hello.world")
    m["hello"] = "Hello, World!"
    # my-bucket/hello.world/hello is already written with contents
    time.sleep(30)
```

However, this works with the local filesystem

```
import fsspec, time

l = fsspec.filesystem("file")
with l.transaction: 
    m = l.get_mapper("/tmp/hello.world") 
    m["hello"] = b"Hello, World!"
    time.sleep(30)
# /tmp/hello.world/hello isn't written until now
```

**Comment by martindurant** [comment]
This may not be clear from the documentation, but the current implementation of `transaction` works only on file-like objects, those created via `.open()`. In the case of local files, the mapper's setitem happens to work via open(), but for s3, a simpler direct-upload codepath (e.g., _pipe_file() ) is available without locally buffering data.

**Comment by ohsqueezy** [comment]
OK, thank you for the explanation! It seems that file appending doesn't work with transactions in general, so I think I'll have to start looking into another approach.
