### ISSUE TITLE
s3fs 0.4.2 version fails with python3.7

### ISSUE THREAD

**Issue by yaelperl1234** [fsspec/s3fs#709]
S3fs (0.4.2) start to use fsspec==2023.3 which doesn't support python3.7.
So I'm getting the following error:

**ModuleNotFoundError: No module named 'importlib.metadata**

> `> import s3fs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/py3.7/lib/python3.7/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/py3.7/lib/python3.7/site-packages/s3fs/core.py", line 8, in <module>
    from fsspec import AbstractFileSystem
  File "/py3.7/lib/python3.7/site-packages/fsspec/__init__.py", line 1, in <module>
    from importlib.metadata import entry_points
ModuleNotFoundError: No module named 'importlib.metadata'`

**Comment by efiop** [comment]
3.7 is not neither by fsspec nor s3fs anymore https://github.com/fsspec/s3fs/blob/4ff92133a9da6b2fe6cfb0fea7223a339c3cf0f8/setup.py#L23

**Comment by efiop** [comment]
Ah, I see you are using 0.4.2 still. You need to manually pin fsspec to an older version if you absolutely have to use that version. There is not much we can do about 0.4.2 🙁

**Comment by yaelperl1234** [comment]
ok, thank you @efiop  !
