### ISSUE TITLE
mv('filepath','filepath') results in deletion of the file rather than no action/inplace move 

### ISSUE THREAD

**Issue by NadimNadimNadimNadimNadim** [fsspec/s3fs#711]
Calling `mv()` of `s3fs.S3FileSystem` with path1==path2 results in deletion. This is not the expected behavior, as a POSIX `mv` results in a message saying they are the same file, and in particular does not result in deletion.

Working example:
```
session = aiobotocore.session.AioSession(profile="dev")
s3 = s3fs.S3FileSystem(session=session)
path_to_file = 'mybucket/file.txt'
s3.mv(
        path1=path_to_file
        path2=path_to_file
)
```
Now, the file in my bucket at location `path_to_file` is deleted.
I have versioning enabled on my bucket for what its worth, so I see the delete marker.

**Comment by martindurant** [comment]
hah, that's funny and I suppose not surprising (mv -> cp then rm). You could propose a PR that converts to a no-op if the two paths are identical, or it could be an exception.

**Comment by NadimNadimNadimNadimNadim** [comment]
haha yeah that's what I figured was happening. Regarding "propose a PR", I've never contributed to an open-source project before. To clarify, you're suggesting I actually make the code change/PR, correct? Or is there another mechanism to ask for a feature/PR without me making it. Just wondering :)

**Comment by martindurant** [comment]
You can ask, but developer time is always limited for open source projects. We could say "don't use the same path twice" and be done :)

But yes, we encourage people to get involved and contribute code changes when they identify a clear problem. https://anaconda.cloud/your-first-oss-contribution

**Comment by NadimNadimNadimNadimNadim** [comment]
@DavidKatz-il Sweet! I like the idea of it being no-op if path1==path2.

**Comment by NadimNadimNadimNadimNadim** [comment]
or perhaps just not deleting it if path1==path2. that way if someone wants to use this to "touch" files they can.

**Comment by DavidKatz-il** [comment]
@martindurant 
Should we do this change on the `fsspec` library [here](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/spec.py#L1032), or only for `s3fs`?

**Comment by martindurant** [comment]
Indeed it probably makes sense to add it upstream in fsspec.
