### ISSUE TITLE
Question about Write in compatible S3 instances

### ISSUE THREAD

**Issue by pedro-ricardo** [fsspec/s3fs#714]
Hello there,
We are testing an S3 compatible storage with s3fs and I'm able to Read fine ..  any kind of writing gives a timeout.

```python
fs = s3fs.S3FileSystem(
    key='xxxxxxxxx',
    secret='xxxxxxxxxxxxx',
    client_kwargs={
        'endpoint_url': 'xxxxxxxxxxxxxxx',
        'region_name': 'xxxxxxxx'},

# Reading and existing file
with fs.open("s3://test01/hello.txt", "rb") as stream:
    print(stream.read())

# Creating a new file
with fs.open("s3://test01/new_hello.txt", "wb") as stream:
    stream.write(b"Hello World\n")
```

On the write part I get the Timeout error:
```log
2023-03-17 15:45:08,784 - s3fs - DEBUG - _upload_chunk -- Upload for <File-like object S3FileSystem, test01/new_hello.txt>, final=True, loc=12, buffer loc=12
2023-03-17 15:45:08,784 - s3fs - DEBUG - commit -- Commit <File-like object S3FileSystem, test01/new_hello.txt>
2023-03-17 15:45:08,784 - s3fs - DEBUG - commit -- One-shot upload of <File-like object S3FileSystem, test01/new_hello.txt>
2023-03-17 15:45:08,785 - s3fs - DEBUG - _call_s3 -- CALL: put_object - ({},) - {'Key': 'new_hello.txt', 'Bucket': 'test01', 'ACL': ''}
2023-03-17 15:46:30,150 - s3fs - DEBUG - _error_wrapper -- Retryable error: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
2023-03-17 15:47:50,974 - s3fs - DEBUG - _error_wrapper -- Retryable error: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
2023-03-17 15:49:17,575 - s3fs - DEBUG - _error_wrapper -- Retryable error: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
2023-03-17 15:50:38,270 - s3fs - DEBUG - _error_wrapper -- Retryable error: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
2023-03-17 15:52:02,233 - s3fs - DEBUG - _error_wrapper -- Retryable error: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
```

My support on this S3 compatible storage tells me that an Open following by a Write was not suppose to work on S3 due to the fact that Objects can not be edited.

So ... Does S3FS library does something special?

**Comment by martindurant** [comment]
As you can see from the logging, s3fs is calling [put_object](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html), an S3 standard endpoint. For longer files, it does do something special in using a multi-part upload, but not here. I can't account for a timeout - any incorrect usage should come back with an error instead.

**Comment by pedro-ricardo** [comment]
Ok, so upon calling the `put_object` I'm are getting a timeout error.... some timeouts latter I get an error about too much tries.
```log
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://xxxxxxxxxxxxxxxxxxxxxx/test01/new_hello.txt"
```
And that happens every time.


We tried to upload files with the `boto3` library like the following:
```python
session = boto3.session.Session()
client = session.client('s3',
    endpoint_url='https://xxxxxxxxxxxxxxx/',
    aws_access_key_id='xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    aws_secret_access_key='xxxxxxxxxxxxxxxxxxxxxxxxxxx'
)
client.upload_file('hello.txt', 'test01')
```
And it works as expected ...

As they don't know `s3fs` and it works using `boto3` this will end up with an excuse from the S3 Support that something is wrong with this library ....
As I don't believe in that, Could you guys tell me how to lead the Support to attack the problem?

**Comment by martindurant** [comment]
Our call is executed by aiobotocore, which is a slightly different way of calling the same underlying botocore routines that boto3 uses. If you are talking with support, they should be able to see the call at their end and have a reply for why it timed out or any other server-side error that appeared.

**Comment by pedro-ricardo** [comment]
I see, 
I managed to upload with `s3cmd` correctly as well ... but I had the same problem when using `aiobotocore` directly.

The following code gives me the same timeouts until it end in maximum try errors
```python
import asyncio
from aiobotocore.session import get_session

async def go():
    session = get_session()
    
    async with session.create_client('s3',
        endpoint_url='xxxxxxxxxxxxxxxxxxxx',
        region_name='xxxxxxxxxxxxxxxxxxx',
        aws_secret_access_key='xxxxxxxxxxxxxx',
        aws_access_key_id='xxxxxxxxxxxxxxxxx') as client:
        
        # Get Object
        response = await client.get_object( Bucket='test01', Key='hello.txt')
        # Read it
        async with response['Body'] as stream:
            print(await stream.read())

        # Upload Object
        resp = await client.put_object(Bucket='test01', Key='new_hello.txt', Body=b"Hello World\n")
        print(resp)
        
loop = asyncio.get_event_loop()
loop.run_until_complete(go())
```

But if I go to test with `botocore` ... than it works again:
```python
from botocore.session import get_session

session = get_session()

client = session.create_client('s3',
    endpoint_url=URL,
    region_name=REGION,
    aws_secret_access_key=SECRET_ACCESS_KEY,
    aws_access_key_id=ACCESS_KEY_ID)
    
# Get Object
response = client.get_object(
    Bucket='aimirim01',
    Key='hello.txt')
# Read it
with response['Body'] as stream:
    print(stream.read())

# Upload Object
resp = client.put_object(
    Bucket='aimirim01',
    Key='new_hello.txt',
    Body=b"Hello World\n")
print(resp)
```

In summary ... so far I tested: 
- boto3: :heavy_check_mark:
- s3fs: :heavy_multiplication_x:
- aiobotocore: :heavy_multiplication_x:
- botocore: :heavy_check_mark:

**It seems like I have to submit an issue to `aiobotocore`**

**Comment by pedro-ricardo** [comment]
as expected then ... the sample code works fine at **s3fs v0.3.5** ... because it used to depended on `boto3` and `botocore`

**Comment by martindurant** [comment]
Yes, please do report it to aiobotocore.
I have anecdotally heard of cases where it fails to redirect for the appropriate region, so rechecking your region argument and setting cache_regions=True on S3FileSystem might help.

I am also developing a rust-based implementation for fsspec, so when it's a little further along, I may ask you to test if it succeeds here where s3fs doesn't.

**Comment by pedro-ricardo** [comment]
Thanks for the attention ... but I'm not sure we will maintain that S3 storage :rofl: 

If we still have it by the time you need that test .. just call :+1:
