### ISSUE TITLE
`cgi` is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by WilliamJamieson** [fsspec/s3fs#716]
`astropy` is seeing failures originating in `s3fs` from:
```
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```
See astropy/astropy#14601 for details.

This is a result of the current release (2023.3.0) requiring a `aiobotocore~=2.4.2` which in turn requires `botocore>=1.27.59,<1.27.60` which does not include the fixes for this warning from boto/botocore#2794.

It looks like #710 will resolve this issue, but these changes do not currently appear in any PyPi releases. Would it be possible for `s3fs` to make a bugfix release with the changes from #710?

**Comment by martindurant** [comment]
Certainly, I'll put a release on my slate. Maybe next week.
