### ISSUE TITLE
Allow silencing FileExpired error to facilitate concurrent read / write?

### ISSUE THREAD

**Issue by cyjeff** [fsspec/s3fs#725]
Hello team, I am facing an issue that the s3fs keeps returning `FileExpired` error and blocks our operation.
Obviously it's caused by a concurrent read write to the same object on S3.

Here is the log I see in our instance. Only restarting the instance can make the operation work again, `clear_instance_cache` and `invalidate_cache` does not seem to help in removing the error once it's raised.

```
  File "/lib/python3.10/site-packages/fsspec/spec.py", line 1700, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/lib/python3.10/site-packages/fsspec/caching.py", line 44, in _fetch
    return self.fetcher(start, stop)
  File "/lib/python3.10/site-packages/s3fs/core.py", line 2162, in _fetch_range
    raise FileExpired(
s3fs.utils.FileExpired: [Errno 16] The remote file corresponding to filename XXX.json and Etag "YYY" no longer exists.
```

Here is my implementation, I tested with a delay to make sure that if a write (from another instance) to identical S3 object happened in between the `open` and `read`, above error will be raised. 

```
s3 = s3fs.S3FileSystem(
    anon=False,
    default_fill_cache=False,  # not seems helping for this issue
    default_cache_type="none",  # not seems helping for this issue
)

with s3.open(path, "r") as f:
    ## time.sleep(1)
    return jsonpickle.decode(f.read(), keys=True)
```

As in our business logic we don't mind reading an older version before the write, it would be great if there is a way to bypass the hash (Etag) check (or make it a warning) rather the blocking the operation. Also please let me know if I am not implementing it in the best way. Thanks!

**Comment by martindurant** [comment]
Let me explain what the error means. When you open() a file, s3fs fetches the file's ETag and stores it, amonstr other information such as the file size. Subsequent read requests require that the target have the given ETag, and this is failing for you if the file got rewritten in the meantime. The reason we have this check (we didn't always), is that if you read part of the file, the file changes, and then you just fetch the next block by range from the new file, you will be seeing a mash of old and new: corrupted data.
For your case, the simplest workaround might be to use `fs.cat` (or `cat_file`) to grab the whole file in one go without the consistency check.

**Comment by cyjeff** [comment]
Thanks for the quick response and explanation!  It's much clearer now how it's working under the hood. I should try to reimplement with `fs.cat` and close this issue once problem solved! 🙏🏼

**Comment by cyjeff** [comment]
It works much better with the `cat` method to download the whole file in our use case. Thanks for the suggestion!
