### ISSUE TITLE
AttributeError: 'S3' object has no attribute '__aenter__'

### ISSUE THREAD

**Issue by Jeppefs** [fsspec/s3fs#753]
We are using Pyarrow to write parquet data sets to S3:
```
 s3 = s3fs.S3FileSystem(session=aws_session._session)
pyarrow.parquest.write_to_dataset(
    pa_table,
    root_path=f"s3://{s3_bucket_name}/{s3_file_key}",
    filesystem=s3,
    partition_cols=partition_cols,
    use_legacy_dataset=True
)
```
We recently upgraded s3fs to 2023.6.0 and other related packages, and now the the following error: 
`AttributeError: 'S3' object has no attribute '__aenter__'`
When adding cached_regions to the s3fs call, we instead get the following error: 
`AttributeError: type object 'S3' has no attribute '__aexit__'`
Of related packages, we use the following versions: 
aiobotocore==2.5.1
boto3==1.26.161
botocore==1.29.161
pandas==2.0.3
pyarrow==12.0.1
s3fs==2023.6.0

**Comment by martindurant** [comment]
Is `aws_session._session` an aiobotocore session?

**Comment by Jeppefs** [comment]
It is not. It is a standard botocore session. I was not aware that s3fs required aiobotocore instead of botocore. I guess that solves it. Thank you.
