### ISSUE TITLE
Use custom url for s3 using AWS_ENDPOINT_URL 

### ISSUE THREAD

**Issue by Kotwic4** [fsspec/s3fs#756]
AWS_ENDPOINT_URL is now supported by the AWS for custom url (for example localhost).
More info about it [docs](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html) and [original github issue](https://github.com/aws/aws-cli/issues/1270). It was merged into botocore in [this pr](https://github.com/boto/botocore/pull/2973).

What I can do with boto:
```python
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

session = boto3.session.Session()
s3_client = session.client(
    service_name="s3",
)
print(s3_client.list_buckets()["Buckets"])
```
What I have to do in s3fs:
```python
import os
import s3fs

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

s3 = s3fs.S3FileSystem(endpoint_url=os.environ["AWS_ENDPOINT_URL"])
print(s3.ls(""))
```

What I would like to do in s3fs:
```python
import os
import s3fs

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

s3 = s3fs.S3FileSystem()
print(s3.ls(""))
```

**Comment by martindurant** [comment]
Assume s3fs will also get this automatically without doing anything as soon as aiobotocore bumps its dependency on botocore. Maybe ask them when they plan to do that. botocore is at 1.31.5, but the [dep](https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L10) is 1.29.161 .

**Comment by Kotwic4** [comment]
ok, created issue there as well

**Comment by dpprdan** [comment]
botocore has been bumped to 1.31.17 in aiobotocore, https://github.com/aio-libs/aiobotocore/pull/1029

**Comment by martindurant** [comment]
s3fs 2023.9.0 uses aiobotocore 2.5.4, which is after the PR linked above. However, 2.6.0 is also out, but we don't have that as our dependency due to https://github.com/conda-forge/aiobotocore-feedstock/issues/68

**Comment by martindurant** [comment]
s3fs does accept `profile=`, please test if this works now for you.

**Comment by dpprdan** [comment]
The following examples all work for me (with config for [play.min.io](https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html#configuration)):

```python
import os
import s3fs

os.environ["AWS_ACCESS_KEY_ID"] = "Q3AM3UQ867SPQQA43P2F"
os.environ["AWS_SECRET_ACCESS_KEY"] = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
os.environ["AWS_ENDPOINT_URL"] = "https://play.min.io:9000"

s3 = s3fs.S3FileSystem()
s3.ls("asiatrip")
```

```python
import os
import s3fs

os.environ["AWS_PROFILE"] = 'play'

s3 = s3fs.S3FileSystem()
s3.ls('asiatrip')
```

```python
import os
import s3fs

s3 = s3fs.S3FileSystem(profile='play')
s3.ls('asiatrip')
```

The latter two with `~/aws/config`

```ini
# https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html
# https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-config

[default]
# "Explicit is better than implicit."

[profile play]
region = us-east-1
services = play-s3

[services play-s3]
S3 =
  endpoint_url = https://play.min.io:9000
  signature_version = s3v4

s3api =
  endpoint_url = https://play.min.io:9000
```

and `~/aws/credentials`

```ini
# https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html

[default]

[play]
aws_access_key_id = Q3AM3UQ867SPQQA43P2F
aws_secret_access_key = zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

This can be closed IMHO.

**Comment by martindurant** [comment]
Thanks for testing
