### ISSUE TITLE
`rm_file` does not invalidate the list cache

### ISSUE THREAD

**Issue by jwa5426** [fsspec/s3fs#761]
I've noticed that [rm_file()](https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1880-L1886) does not invalidate the list cache as [rm](https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1908) does. This can be demonstrated by calling `rm_file(file_path)` followed by `ls()`.  `file_path` will still be listed despite being deleted.

**Comment by jwa5426** [comment]
Note: `rm(file_path)` followed by `ls()` does not list the deleted `file_path`

**Comment by ianthomas23** [comment]
I've confirmed this, and there is a fix in #762.

**Comment by jwa5426** [comment]
@ianthomas23 thanks!
