### ISSUE TITLE
AttributeError: __aenter__ with aiobotocore 2.5.3

### ISSUE THREAD

**Issue by rdbisme** [fsspec/s3fs#767]
Hello, not sure this is a `aiobotocore` issue or `fsspec` issue. But basically what I've reported here: https://github.com/aio-libs/aiobotocore/issues/1031. 

A code that was working with `aiobotocore 2.5.2` broke this morning when `aiobotocore 2.5.3` shipped. The interesting bit is that we can reproduce only on Docker and that when erroring, it suggests `AttributeError: __aenter__. Did you mean: '_details'?` that seems related to an `fsspec` object. 

Reverting to 2.5.2 works. 

A reproduction is here: https://github.com/aio-libs/aiobotocore/issues/1031#issuecomment-1667899504 (but only on Docker)

**Comment by martindurant** [comment]
(moved issue to s3fs)

Notice that s3fs has an [exact pin](https://github.com/fsspec/s3fs/blob/main/requirements.txt#L1) on aiobotocore. 

For sure, we want to work out what changed upstream, and make the next release depend on the latest available package.

**Comment by josiahjohnston** [comment]
Thanks for being so responsive! This bit my group also, and the bug reports were super helpful.

FWIW, [thehesiod](https://github.com/thehesiod) fixed the issue about 45 minutes ago and posted a new version.

**Comment by rdbisme** [comment]
Yep! Saw that. I guess we can close this then! Thanks everyone for the amazing reactivity!
