### ISSUE TITLE
`glob` result for s3 folder different in `2023.6.0` and `2023.9.0` versions

### ISSUE THREAD

**Issue by anmyachev** [fsspec/s3fs#783]
Reproducer:
```python
import fsspec

file_path = "s3://modin-datasets/testing/multiple_csv/"
fs, _ = fsspec.core.url_to_fs(file_path, anon=True)

fs.glob(file_path)
# ['modin-datasets/testing/multiple_csv/test_data0.csv', 'modin-datasets/testing/multiple_csv/test_data1.csv'] in 2023.6.0
#  ['modin-datasets/testing/multiple_csv'] in 2023.9.0 
```

Core reason most likely - https://github.com/fsspec/s3fs/pull/769

**Comment by martindurant** [comment]
cc @john-jam

**Comment by john-jam** [comment]
As indicated in the description of [this PR](https://github.com/fsspec/filesystem_spec/pull/1329), a new rule was added to be posix compliant: _when using a trailing slash in globs, it returns only directories._ (and [here is the code update](https://github.com/fsspec/filesystem_spec/pull/1329/files#diff-9e28a72564624d8305a58b77c04c514d15e016b61899fd507b52b30388ef6ab6R787-R790) that handles that).

The bash and python implementation follow this rule but we can revert it in `fsspec` if it is not wanted, what do you think @martindurant @ianthomas23 ?

**Comment by ianthomas23** [comment]
I think we should always aim for posix compliance.

**Comment by anmyachev** [comment]
> I think we should always aim for posix compliance.

Agree.

> The glob that will match your expected result would be s3://modin-datasets/testing/multiple_csv/*.

We will have to write a logic that will add `*` to the end of a URL, for backwards compatibility, but this is ok.

**Comment by martindurant** [comment]
Thanks for your understanding, @anmyachev
