### ISSUE TITLE
Support `size=` in `S3File`

### ISSUE THREAD

**Issue by jrbourbeau** [fsspec/s3fs#794]
Currently the base `AbstractBufferedFile` class supports a `size=` keyword, but `s3fs` doesn't take advantage of it. It'd be nice if we did so we could accessing S3 unnecessarily 

cc @martindurant, who I was on a call earlier today with about this

**Comment by martindurant** [comment]
The specific issue, is that `open()`, producing an S3File will call `info()` on that file. If the fie details don't happen to be in the directory cache, this means a call to s3, which is not itself cached (as it would be only one file in the directory, not the complete listing). In @jrbourbeau 's case, we know the sizes of the files by other means, so we should be able to skip the lookup, as can be done for instance with HTTPFileSystem.

**Comment by martindurant** [comment]
```
# after any initial call which does SSL and checks credentials. 
In [4]: %time f = fs.open("mymdtemp/icesat2-4.01.json")
CPU times: user 4.07 ms, sys: 1.76 ms, total: 5.83 ms
Wall time: 57.3 ms

In [5]: fs.invalidate_cache()

In [6]: %time f = fs.open("mymdtemp/icesat2-4.01.json", size=100)
CPU times: user 110 µs, sys: 0 ns, total: 110 µs
Wall time: 113 µs
```
