### ISSUE TITLE
ImportError: cannot import name '_DEFAULT_ADVISORY_REFRESH_TIMEOUT' from 'botocore.credentials'

### ISSUE THREAD

**Issue by iamrc90** [fsspec/s3fs#804]
I am getting the following error suddenly on my spark job in EMR. Could anyone please help me with this error?
Please let me know if any more details are required ? 

Thanks

```

  File "/usr/local/lib/python3.7/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 28, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.7/site-packages/aiobotocore/session.py", line 14, in <module>
    from .credentials import AioCredentials, create_credential_resolver
  File "/usr/local/lib/python3.7/site-packages/aiobotocore/credentials.py", line 14, in <module>
    from botocore.credentials import (
ImportError: cannot import name '_DEFAULT_ADVISORY_REFRESH_TIMEOUT' from 'botocore.credentials' (/usr/local/lib/python3.7/site-packages/botocore/credentials.py)

```

**Comment by martindurant** [comment]
Please check your versions of s3fs, fsspec, aiobotocore, botocore

s3fs 2023.9.2 requires
- fsspec 2023.9.2
- aiobotocore 2.5.4
  - which needs botocore 1.31.17, aiohttp >=3.3.1,<4.0.0

**Comment by iamrc90** [comment]
@martindurant 
Thanks for the inputs. Below are my versions. Please suggest. 
- s3fs 2023.1.0
- fsspec 2023.1.0
- aiobotocore 2.4.2 
     - botocore 1.24.46
     - aiohttp 3.8.5

**Comment by martindurant** [comment]
aiobotocore 2.4.2 requires botocore 1.27.59
https://github.com/aio-libs/aiobotocore/blob/2.4.2/setup.py#L10

**Comment by iamrc90** [comment]
Thanks @martindurant 
It works.
