### ISSUE TITLE
find/glob on a bucket root needs ListBuckets permissions in some instances - previously didnt

### ISSUE THREAD

**Issue by artttt** [fsspec/s3fs#811]
When the user doesn't have ListBuckets permissions
previously with 
fsspec.__version__  '2023.3.0'
s3fs.__version__  '2023.3.0'

 `find` and `glob` worked in all the examples below.

With version
fsspec.__version__  '2023.9.2'
s3fs.__version__  '2023.9.2'

 `find` and `glob` return permission errors in some cases.
```python
s3path = 's3://example_bucket'
 
#this fails
fs.find(s3path,maxdepth=1,withdirs=True)
 
#this works
fs.find(s3path,withdirs=True)
 
#fails
fs.glob(f"{s3path}/*")
 
#works
fs.glob(f"{s3path}/**")
```

**Comment by jbsilva** [comment]
Same in s3fs version 2024.2.0
