### ISSUE TITLE
Return offset-aware datetimes

### ISSUE THREAD

**Issue by malmans2** [fsspec/s3fs#817]
`s3fs` returns offset-naive datetimes, whereas https://github.com/fsspec/filesystem_spec/pull/1314 introduced datetimes at UTC in `fsspec`. 

I often get errors because operations mixing offset-naive and offset-aware datetimes are not allowed.
Here is an example:
```python
fsspec.filesystem("file").modified(...) - fsspec.filesystem("s3").modified(...)
# TypeError: can't subtract offset-naive and offset-aware datetimes
```

Would it be possible to introduce offset-aware datetimes in `s3fs` as well?

**Comment by martindurant** [comment]
Actually, I think I would go the other way: local files don't actually have a timezone. We should decide one way or another, and make sure `modified()` behaves the same everywhere, which might take a little effort.

**Comment by malmans2** [comment]
mmm, good point. Thinking more about it, I think it's OK if filesystem implementations can decide whether to return offset-aware or offset-naive datetimes. 

However, I think they should return offset-aware datetimes when they can. I don't like what it's done [here](https://github.com/fsspec/s3fs/blob/2c074502c2d6a9be0d3f05eb678f4cc5add2e7e5/s3fs/core.py#L1984) because we lose an important information.

As you said, local files don't actually have a timezone. I believe right now fsspec assumes that time infos use the system local timezone and converts to utc. Looks like a reasonable assumption to me, but if it's not a good assumption I agree that `created` and `modified` should return offset-naive datetimes.
