### ISSUE TITLE
s3fs file-like object is not equal to itself

### ISSUE THREAD

**Issue by krehm** [fsspec/s3fs#827]
I want to read an hdf5 file via fsspec with s3fs as the backend (minio currently provides S3).  I open a file-like object via 
    flobj = S3FileSystem.open('s3://dlio-bucket/data/s3/train/0/img_00_of_64.hdf5', mode='rb')
and then call 
    return h5py.File(flobj, 'rb')
to return the opened hdf5 file to the caller for reading.  This fails because of a test in the h5py class File __init__ method.  The exception that is thrown is:
    ValueError: Invalid value of 'fileobj' argument; must equal to file-like object if specified.
The error occurs because the S3FileSystem flobj object is not equal to itself.  I wonder if this is a bug, and if not, then is there a way to work around it?

The error comes from h5py/_hl/files.py, class File, method __init__().   The code that fails is:
                if kwds.get('fileobj', name) != name:
                    raise ValueError("Invalid value of 'fileobj' argument; "
                                     "must equal to file-like object if specified.")
kwds is an empty dictionary in this case, so the test above is effectively:
                if name != name:
which returns True.  I breakpointed just before the test to verify, and get the following:

(Pdb) p name
<File-like object S3FileSystem, dlio-bucket/data/s3/train/0/img_00_of_64.hdf5>
(Pdb) print(name is name)
True
(Pdb) print(name != name)
True

I don't understand why the 'name' object is not equal to itself.  Perhaps it is coming from the __ne__ method, but I wasn't able to find the code for that.  Thoughts?

**Comment by martindurant** [comment]
The current definition of equal is:
```
    def __eq__(self, other):
        """Files are equal if they have the same checksum, only in read mode"""
        return self.mode == "rb" and other.mode == "rb" and hash(self) == hash(other)
```
(in fsspec.spec.AbstractBufferedFile)
where `hash` depends on the file's "details" (size, path, timestamp, etag...).

I suppose `self is other` could be a reasonable thing allow here. I suspect that's what HDF should be doing anyway.

**Comment by krehm** [comment]
I just opened PR 1466 against fsspec to address this, as suggested by @martindurant above.
