### ISSUE TITLE
Question: is awscrt useful ?

### ISSUE THREAD

**Issue by mdespriee** [fsspec/s3fs#867]
The awscrt package is supposed to increase performance in the use of s3 https://aws.amazon.com/fr/blogs/storage/improving-amazon-s3-throughput-for-the-aws-cli-and-boto3-with-the-aws-common-runtime/

From my understanding, bringing it in the environment is enough for botocore to use it, yet I see no clear improvement at all on my app using s3fs.

Has anyone managed to get improvement with it?

**Comment by martindurant** [comment]
Any performance improvements seem to happen by splitting up/downloads into pieces and sending them concurrently, which we already do. In any case, it only hooks into boto3, whereas we use aiobotocore for its async capabilities, so it's far from obvious how it could integrate with s3fs.

**Comment by mdespriee** [comment]
Thanks @martindurant 
I think botocore [loads it if present](https://github.com/boto/botocore/blob/1be45c52cf3b743186f9191e7f53d66eefae23cd/botocore/useragent.py#L499), but it doesn't appear to have any effect.

I'll follow-up with aiobotocore guys.
