### ISSUE TITLE
upload function didn't recognize the file path having "[]".

### ISSUE THREAD

**Issue by realzhipeng** [fsspec/s3fs#875]
When using the upload function, it will meet the FileNotFoundError error if the file path contains the "[]"symbol like "001_AG230060...-01.by[22]"

**Comment by martindurant** [comment]
You should be able to use put_file to avoid expanding the URL (because the `[..]` looks like a glob pattern).

See also https://github.com/fsspec/filesystem_spec/pull/1558

**Comment by realzhipeng** [comment]
@martindurant that's interesting. Now I use put_file, which perform much better. But I didn't get the difference between put_file and upload... Maybe add a bit intro into the Documents?

**Comment by martindurant** [comment]
upload() is the same as put(), and works on bulk uploads of possibly many files. Docstring:

>       Copies a specific file or tree of files (if recursive=True). If rpath
>       ends with a "/", it will be assumed to be a directory, and target files
>       will go within.
>       The put_file method will be called concurrently on a batch of files. ...

**Comment by realzhipeng** [comment]
Good to know that. Thank you for the infor.
