### ISSUE TITLE
find returns parent directory if no object matches the prefix

### ISSUE THREAD

**Issue by chorng** [fsspec/s3fs#911]
With the following contents in the bucket:
```
bucket/dir1/file1
bucket/dir1/file2
bucket/dir1/img1
```
When making a query with `find('bucket/dir1', prefix='file')`, it returns `['bucket/dir1/file1', 'bucket/dir1/file2']` as expectation. When making a query with `find('bucket/dir1', prefix='file3')`, I expect that it returns an empty list `[]` as there's no object matches the prefix `file3`; however, a list containing only the parent directory is returned `['bucket/dir1']`. 

This behaviour seems inconsistent to me. Is it intended? If yes, what is the reasoning?

**Comment by martindurant** [comment]
Indeed, it sounds like a bug. If you have any time to trace it down, it would be appreciated - especially since you already have a test case.

**Comment by chorng** [comment]
@martindurant I've prepared a fix along with a test. Please have a look.
