### ISSUE TITLE
Supporting `mode='x'` with conditional requests to prevent overwriting

### ISSUE THREAD

**Issue by gtebbutt** [fsspec/s3fs#919]
I'm a new user of this library, so apologies in advance if I've missed something obvious! 

I was hoping to use it as a drop-in replacement for the native `open()` function, but my existing code uses `mode='x'` to prevent accidental overwriting in case of a filename collision. I couldn't see any indication that's supported here, but I did find that S3 has recently added support for [conditional requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-writes.html), and Cloudflare R2 (which I'm using right now) supports [the same headers](https://developers.cloudflare.com/r2/api/s3/extensions/#conditional-operations-in-putobject), so it looks like it'd now be possible to add in a way that's not subject to race conditions. 

Is this something that's planned or would be of interest? Seems like it'd be a useful addition that fits nicely within the scope of matching the existing python filesystem API.

**Comment by gtebbutt** [comment]
Ah, I've just realised there's an open PR (#917) from a few days ago implementing exactly this! Problem solved, by the look of it!

**Comment by martindurant** [comment]
Specifically: it will work locally, but the s3 PR is not yet done, because the mocker library doesn't implement it :|. I believe it does work, and I intend to implement it for GCS amd azure and maybe others. None of this is released.

**Comment by gtebbutt** [comment]
Got it, and thanks for the quick follow up - I'll be fine running it directly from the branch for now, it should still save me a good amount of time being able to use with my code as-is.
